//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicPlayer.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Order playback 的本地化字符串。
        /// </summary>
        public static string MainWindow_ArrowRightButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_ArrowRightButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string MainWindow_CloseButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_CloseButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        public static string MainWindow_DrawerHost_Duration_Header {
            get {
                return ResourceManager.GetString("MainWindow_DrawerHost_Duration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singer 的本地化字符串。
        /// </summary>
        public static string MainWindow_DrawerHost_Singer_Header {
            get {
                return ResourceManager.GetString("MainWindow_DrawerHost_Singer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Song Title 的本地化字符串。
        /// </summary>
        public static string MainWindow_DrawerHost_SongTitle_Header {
            get {
                return ResourceManager.GetString("MainWindow_DrawerHost_SongTitle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlist 的本地化字符串。
        /// </summary>
        public static string MainWindow_HamburgerMenuButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_HamburgerMenuButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import songs 的本地化字符串。
        /// </summary>
        public static string MainWindow_ImportSongsButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_ImportSongsButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string MainWindow_MinimizeButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_MinimizeButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string MainWindow_PauseButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_PauseButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string MainWindow_PlayButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_PlayButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single tune circulation 的本地化字符串。
        /// </summary>
        public static string MainWindow_RepeatdButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_RepeatdButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string MainWindow_SettingButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_SettingButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random broadcast 的本地化字符串。
        /// </summary>
        public static string MainWindow_ShuffleButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_ShuffleButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous song 的本地化字符串。
        /// </summary>
        public static string MainWindow_StepBackwardButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_StepBackwardButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next song 的本地化字符串。
        /// </summary>
        public static string MainWindow_StepForwardButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_StepForwardButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        public static string MainWindow_VolumeButton_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_VolumeButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music Player 的本地化字符串。
        /// </summary>
        public static string MainWindow_WindowTitle {
            get {
                return ResourceManager.GetString("MainWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_CancelButton_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_ChineseLanguageLabel_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_ChineseLanguageLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_DarkLabel_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_DarkLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_EnglishLanguageLabel_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_EnglishLanguageLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_LanguageTextBlock_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_LanguageTextBlock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_LightLabel_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_LightLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_SaveButton_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_SaveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string SettingsDialog_ThemeTextBlock_Content {
            get {
                return ResourceManager.GetString("SettingsDialog_ThemeTextBlock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected {0} songs, successfully imported {1} songs 的本地化字符串。
        /// </summary>
        public static string Snackbar_ImportSongsMessage {
            get {
                return ResourceManager.GetString("Snackbar_ImportSongsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved successfully 的本地化字符串。
        /// </summary>
        public static string Snackbar_SettingsSaveMessage {
            get {
                return ResourceManager.GetString("Snackbar_SettingsSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string Snackbar_WelcomeMessage {
            get {
                return ResourceManager.GetString("Snackbar_WelcomeMessage", resourceCulture);
            }
        }
    }
}
